### ISSUE TITLE
Wrong loop type

### ISSUE THREAD

**Issue by Moriarty1982** [owensjrw/tic_tac_toe#3]
https://github.com/owensjrw/tic_tac_toe/blob/8c049ade0aeb1d06bec8bb0d800b9efef84290fc/tictactoe.c#L31

you can use a simple while(1) and break here:
https://www.geeksforgeeks.org/difference-while1-while0-c-language/

**Comment by owensjrw** [comment]
Per the reference listed:

It is not advisable to use while(1) in real-world because it increases the CPU usage and also blocks the code i.e one cannot come out from the while(1) until the program is closed manually.

Although I think both our implementations have the same result and execution.

**Comment by Moriarty1982** [comment]
The diff is, that while(true) / while(1) is easier to read then the for loop.
