### ISSUE TITLE
DRY: Don't repeat yourself

### ISSUE THREAD

**Issue by Moriarty1982** [owensjrw/tic_tac_toe#4]
https://github.com/owensjrw/tic_tac_toe/blob/8c049ade0aeb1d06bec8bb0d800b9efef84290fc/tictactoe.c#L34

printf("%c | %c | %c\n", tictactoe_board[0],tictactoe_board[1],tictactoe_board[2]);
puts("---------");
printf("%c | %c | %c\n", tictactoe_board[3],tictactoe_board[4],tictactoe_board[5]);
puts("---------");
printf("%c | %c | %c\n", tictactoe_board[6],tictactoe_board[7],tictactoe_board[8]);

This code is used more then one time and do alsways the same, use an function to call it:
https://www.tutorialspoint.com/cprogramming/c_functions.htm

**Comment by owensjrw** [comment]
Thank you. Normally for a project like this we would use user defined functions to keep from repeating. The request for help I received was for a tic-tac-toe game that had zero user defined functions.

**Comment by Moriarty1982** [comment]
Alright, thx
